In [1]:
import pandas as pd

In [11]:
df_valid = pd.read_csv('valid/df_valid_20.csv')

In [12]:
df_valid.gender.value_counts().sort_index().to_numpy() + df_train.gender.value_counts().sort_index().to_numpy()

array([1654, 1046])

In [4]:
## male to female

In [5]:
correction = ['001498-1_male_Asian_23', '004432_male_Asian_43', '005223_male_Asian_22']

for df in [df_train, df_valid]:
    idxs = df['path'].isin(correction)
    df.loc[idxs, 'gender'] = 'female'

In [6]:
df_valid.gender.value_counts().sort_index().to_numpy() + df_train.gender.value_counts().sort_index().to_numpy()

array([1660, 1040])

In [ ]:
## female to male

In [7]:
correction = ['001720_female_Asian_18',
            '006359_female_Asian_18',
            '006360_female_Asian_18',
            '006361_female_Asian_18',
            '006362_female_Asian_18',
            '006363_female_Asian_18',
            '006364_female_Asian_18']

In [8]:
for df in [df_train, df_valid]:
    idxs = df['path'].isin(correction)
    df.loc[idxs, 'gender'] = 'male'

In [9]:
df_valid.gender.value_counts().sort_index().to_numpy() + df_train.gender.value_counts().sort_index().to_numpy()

array([1654, 1046])

In [10]:
df_valid.to_csv('valid/df_valid_20.csv', index=False)
df_train.to_csv('train/df_train_20.csv', index=False)